- name: install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present

- name: create /opt/loki directory
  ansible.builtin.file:
    path: /opt/loki
    state: directory
    owner: root
    group: root
    mode: 0755

- name: template loki testing config file
  ansible.builtin.template:
    src: templates/loki_test.yml.j2
    dest: /etc/loki/loki_test.yml
    owner: root
    group: root
    mode: 0644

- name: make directory for loki config
  ansible.builtin.file:
    path: /etc/loki
    state: directory
    owner: root
    group: root
    mode: 0644

- name: template loki config file
  ansible.builtin.template:
    src: templates/loki.yml.j2
    dest: /etc/loki/loki.yml
    owner: root
    group: root
    mode: 0644

- name: Check loki version
  block:
    - name: check loki version
      ansible.builtin.command: sudo /opt/loki/loki --version  -config.file /etc/loki/loki.yml
      register: loki_version_check
      when: binary.stat.exists
      changed_when: false

    - name: Show loki version
      ansible.builtin.debug:
        msg: "{{  loki_version_check | regex_search('\\d.\\d+.\\d+')  }} is installed, and {{  loki_version  }} is the newest"

  rescue:
    - name: check loki version
      ansible.builtin.command: sudo /opt/loki/loki --version  -config.file /etc/loki/loki_test.yml
      register: loki_version_check
      when: binary.stat.exists
      changed_when: false

    - ansible.builtin.file:
        path: /etc/loki/loki_test.yml
        state: absent

    - name: Show loki version
      ansible.builtin.debug:
        msg: "{{  loki_version_check | regex_search('\\d.\\d+.\\d+')  }} is installed, and {{  loki_version  }} is the newest"

- name: check if binary exists
  ansible.builtin.stat:
    path: /opt/loki/loki
  register: binary

- name: install loki if its not present
  ansible.builtin.unarchive:
    src: "https://github.com/grafana/loki/releases/download/v\
         {{  loki_version  }}/loki-linux-amd64.zip"
    dest: /opt/loki/
    remote_src: true
  tags:
    - loki
  when: (not binary.stat.exists)
  notify: 
    - move loki binary

- name: reinstall loki if different version is defined in variable
  ansible.builtin.unarchive:
    src: "https://github.com/grafana/loki/releases/download/v\
         {{  loki_version  }}/loki-linux-amd64.zip"
    dest: /opt/loki/
    remote_src: true
  tags:
    - loki
  when: (loki_version_check | regex_search('\d.\d+.\d+') != loki_version)
  notify: 
    - restart loki
    - move loki binary

- name: template systemd unit file
  ansible.builtin.template:
    src: templates/loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: 0755
  tags:
    - loki
  notify: reload systemd daemon

- name: enable and start loki service
  ansible.builtin.systemd:
    name: loki
    enabled: true
    state: started
  tags:
    - loki
